// react_hooks/src/recipe.js
import { useState } from 'react';

import IngredientList from './ingredient_list';

export default function Recipe() {
  const [ingredients, setIngredients] = useState([]);
  const [newName, setNewName] = useState("");

  function handleChange(event) {
    setNewName(event.target.value);
  }

  function handleSubmit(event) {
    event.preventDefault();
    const newIngredient = {
      id: ingredients.length + 1,
      amount: 1,
      name: newName,
    };
    setIngredients([...ingredients, newIngredient]);
  }

  function handleRemove(id) {
    const newIngredients = ingredients.filter((ingredient) => {
      return (ingredient.id !== id);
    });
    setIngredients(newIngredients);
  }

  function handleAmountChange(action, id) {
    const newIngredients = ingredients.map((ingredient) => {
      if (ingredient.id === id) {
        const toAdd = (action === "increase") ? 1 : -1;
        ingredient.amount += toAdd;
      }
      return ingredient;
    });
    setIngredients(newIngredients);
  }

  return (
    <div className="mt-4 mb-2">
      <div><strong>Ingredients</strong></div>
      <table className="table">
        <thead>
          <tr>
            <th className="w-25">Amount</th>
            <th className="w-50">Name</th>
            <th className="w-25"></th>
          </tr>
        </thead>
        <IngredientList
           amountChangeHandler={handleAmountChange}
           removeHandler={handleRemove}
           ingredients={ingredients}
        />
      </table>
      <div className="mt-5">
        <form id="new-ingredient" onSubmit={handleSubmit} >
          <label>
            Name:
            <input type="text" name="name" value={newName} onChange={handleChange} className="form-control" />
          </label>
          <button type="submit" className="btn btn-success">Add Ingredient</button>
        </form>
      </div>
    </div>
  );
}

// vue/src/components/Recipe.vue
<script>
import IngredientList from "./IngredientList.vue"

export default {
  components: {
    IngredientList,
  },
  methods: {
    addIngredient(event) {
      event.preventDefault()
      this.ingredients.push({
        id: this.ingredients.length + 1,
        name: this.newName,
        amount: 1
      })
      this.newName = ""
    },
    increaseAmount(id, by) {
      for (const ingredient of this.ingredients) {
        if (ingredient.id === id) {
          ingredient.amount += by
        }
      }
    },
    removeIngredient(id) {
      const ingredient = this.ingredients.find((ingredient) => {
        return (id === ingredient.id)
      })
      this.ingredients.splice(this.ingredients.indexOf(ingredient), 1)
    }
  },
  data() {
    return {
      ingredients: [],
      newName: ""
    }
  }
}
</script>

<template>
  <div class="mt-4 mb-2">
    <div><strong>Ingredients</strong></div>
    <table class="table">
      <thead>
        <tr>
          <th class="w-25">Amount</th>
          <th class="w-50">Name</th>
          <th class="w-25"></th>
        </tr>
      </thead>
      <IngredientList 
        :ingredients="ingredients"
        @increaseAmount="increaseAmount"
        @removeIngredient="removeIngredient"
      />
    </table>
    <div class="mt-5">
      <form id="new-ingredient" @submit="addIngredient" >
        <label>
          Name:
          <input type="text" name="name" v-model="newName" class="form-control">
        </label>
        <button type="submit" class="btn btn-success">Add Ingredient</button>
      </form>
    </div>
  </div>
</template>
