// vue/src/components/IngredientList.vue
<script>
  import Ingredient from "./Ingredient.vue"

  export default {
    components: {
      Ingredient
    },
    emits: ["increaseAmount", "removeIngredient"],
    props: ["ingredients"],
  }
</script>

<template>
  <tbody id="ingredient-list">
    <Ingredient
      v-for="ingredient in ingredients"
      :key="ingredient.id.toString()"
      :id="ingredient.id"
      :name="ingredient.name"
      :amount="ingredient.amount"
      @increaseAmount="(id, by) => $emit('increaseAmount', id, by)"
      @removeIngredient="(id) => $emit('removeIngredient', id)"
    />
  </tbody>
</template>

// react_classes/src/ingredient_list.js
import React from 'react';

import Ingredient from './ingredient';

class IngredientList extends React.Component {
  render() {
    const ingredients = this.props.ingredients.map((ingredient) =>
      <Ingredient
        key={ingredient.id.toString()}
        id={ingredient.id}
        name={ingredient.name}
        amount={ingredient.amount}
        amountChangeHandler={this.props.amountChangeHandler}
        removeHandler={this.props.removeHandler}
      />
    );

    return (
      <tbody id="ingredient-list">
        {ingredients}
      </tbody>
    );
  }
}

export default IngredientList;
